"""
ORM Models for Optic Shield Backend

Defines database entities:
- Camera: CCTV metadata, geo-coordinates, health status
- Alert: Threat incidents with severity, confidence, keyframe URLs, consensus status
- AuditLedger: SHA-256 blockchain records for tamper-evident logging
"""

from __future__ import annotations

import enum
import hashlib
import json
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.database import Base


class CameraStatus(enum.Enum):
    """Camera operational status."""

    ONLINE = "online"
    OFFLINE = "offline"
    DEGRADED = "degraded"
    MAINTENANCE = "maintenance"
    TAMPERED = "tampered"


class AlertSeverity(enum.Enum):
    """Alert severity levels (matching edge definitions)."""

    INFO = 1
    WARNING = 2
    CRITICAL = 3


class AlertType(enum.Enum):
    """Types of alerts generated by the system."""

    GEOFENCE_INTRUSION = "geofence_intrusion"
    SUSPICIOUS_BEHAVIOR = "suspicious_behavior"
    WATCHLIST_MATCH = "watchlist_match"
    PLATE_RECOGNIZED = "plate_recognized"
    CAMERA_TAMPERED = "camera_tampered"
    CAMERA_BLINDED = "camera_blinded"
    CAMERA_FROZEN = "camera_frozen"
    CAMERA_BLURRED = "camera_blurred"
    IR_FAILURE = "ir_failure"
    STREAM_DEGRADED = "stream_degraded"
    GEO_DRIFT = "geo_drift"


class AlertStatus(enum.Enum):
    """Alert lifecycle status."""

    PENDING = "pending"
    ACKNOWLEDGED = "acknowledged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    ESCALATED = "escalated"


class ConsensusStatus(enum.Enum):
    """Multi-source consensus verification status."""

    NONE = "none"
    PENDING = "pending"
    VERIFIED = "verified"
    CONFLICT = "conflict"
    REJECTED = "rejected"


class Camera(Base):
    """
    Camera/CCTV device metadata and configuration.

    Represents a physical camera deployed at border outposts.
    """

    __tablename__ = "cameras"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(
        PG_UUID(as_uuid=False),
        unique=True,
        nullable=False,
        index=True,
        comment="Universally unique identifier for edge device",
    )

    # Identification
    name: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    serial_number: Mapped[Optional[str]] = mapped_column(String(50), unique=True, nullable=True)

    # Network
    rtsp_url: Mapped[str] = mapped_column(String(500), nullable=False)
    ip_address: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)
    mac_address: Mapped[Optional[str]] = mapped_column(String(17), nullable=True)

    # Location (WGS84)
    latitude: Mapped[float] = mapped_column(nullable=False, comment="GPS latitude in decimal degrees")
    longitude: Mapped[float] = mapped_column(nullable=False, comment="GPS longitude in decimal degrees")
    altitude: Mapped[Optional[float]] = mapped_column(nullable=True, comment="Altitude in meters")
    heading: Mapped[Optional[float]] = mapped_column(nullable=True, comment="Camera heading in degrees (0-360)")
    tilt: Mapped[Optional[float]] = mapped_column(nullable=True, comment="Camera tilt in degrees")
    fov_horizontal: Mapped[Optional[float]] = mapped_column(nullable=True, comment="Horizontal field of view")
    fov_vertical: Mapped[Optional[float]] = mapped_column(nullable=True, comment="Vertical field of view")

    # Operational
    status: Mapped[CameraStatus] = mapped_column(
        Enum(CameraStatus, native_enum=False),
        default=CameraStatus.OFFLINE,
        nullable=False,
        index=True,
    )
    health_score: Mapped[int] = mapped_column(Integer, default=100, nullable=False)
    last_heartbeat: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    last_frame_timestamp: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Configuration
    resolution_width: Mapped[int] = mapped_column(Integer, default=1920)
    resolution_height: Mapped[int] = mapped_column(Integer, default=1080)
    fps: Mapped[float] = mapped_column(default=30.0)
    codec: Mapped[str] = mapped_column(String(20), default="H264")
    bitrate_kbps: Mapped[int] = mapped_column(Integer, default=4096)

    # Analytics config (JSON)
    analytics_config: Mapped[dict[str, Any]] = mapped_column(
        JSON,
        default=lambda: {},
        nullable=False,
        comment="Per-camera analytics configuration",
    )

    # Encryption
    encryption_key_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    deployed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    decommissioned_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    alerts: Mapped[list["Alert"]] = relationship(
        "Alert",
        back_populates="camera",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )
    audit_logs: Mapped[list["AuditLedger"]] = relationship(
        "AuditLedger",
        back_populates="camera",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )

    __table_args__ = (
        Index("ix_cameras_location", "latitude", "longitude"),
        Index("ix_cameras_status_heartbeat", "status", "last_heartbeat"),
    )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary with datetime serialization."""
        data = super().to_dict()
        for key, value in data.items():
            if isinstance(value, datetime):
                data[key] = value.isoformat()
            elif isinstance(value, enum.Enum):
                data[key] = value.value
        return data


class Alert(Base):
    """
    Threat incident alert with full context.

    Generated by edge analytics and sent to central backend.
    """

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(
        PG_UUID(as_uuid=False),
        unique=True,
        nullable=False,
        index=True,
    )

    # Camera reference
    camera_id: Mapped[int] = mapped_column(
        ForeignKey("cameras.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Alert classification
    alert_type: Mapped[AlertType] = mapped_column(
        Enum(AlertType, native_enum=False),
        nullable=False,
        index=True,
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, native_enum=False),
        nullable=False,
        index=True,
    )
    status: Mapped[AlertStatus] = mapped_column(
        Enum(AlertStatus, native_enum=False),
        default=AlertStatus.PENDING,
        nullable=False,
        index=True,
    )

    # Detection details
    confidence: Mapped[float] = mapped_column(nullable=False, comment="Detection confidence 0.0-1.0")
    confidence_breakdown: Mapped[Optional[dict[str, Any]]] = mapped_column(JSON, nullable=True)

    # Object tracking
    track_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True)
    object_class: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    object_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Geofence details
    geofence_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    intersection_point: Mapped[Optional[dict[str, float]]] = mapped_column(JSON, nullable=True)
    penetration_depth: Mapped[Optional[float]] = mapped_column(nullable=True)
    distance_to_boundary: Mapped[Optional[float]] = mapped_column(nullable=True)

    # Trajectory prediction
    predicted_trajectory: Mapped[Optional[list[dict[str, float]]]] = mapped_column(JSON, nullable=True)
    prediction_horizon_seconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Pose/behavior details
    behavior_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    behavior_metrics: Mapped[Optional[dict[str, float]]] = mapped_column(JSON, nullable=True)

    # Face recognition
    watchlist_match_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    watchlist_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    face_similarity: Mapped[Optional[float]] = mapped_column(nullable=True)

    # License plate
    plate_text: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    plate_state: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    plate_confidence: Mapped[Optional[float]] = mapped_column(nullable=True)

    # Camera health
    health_alert_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    health_metrics: Mapped[Optional[dict[str, float]]] = mapped_column(JSON, nullable=True)

    # Keyframe references
    keyframe_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    keyframe_thumbnail_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    keyframe_size_bytes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    keyframe_timestamp: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Additional context (JSON)
    metadata: Mapped[dict[str, Any]] = mapped_column(
        JSON,
        default=lambda: {},
        nullable=False,
    )

    # Consensus verification
    consensus_status: Mapped[ConsensusStatus] = mapped_column(
        Enum(ConsensusStatus, native_enum=False),
        default=ConsensusStatus.NONE,
        nullable=False,
    )
    consensus_sources: Mapped[Optional[list[str]]] = mapped_column(JSON, nullable=True)
    consensus_timestamp: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Timestamps
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Timestamp when edge detected the event",
    )
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Timestamp when backend received the alert",
    )
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Relationships
    camera: Mapped["Camera"] = relationship("Camera", back_populates="alerts")
    audit_logs: Mapped[list["AuditLedger"]] = relationship(
        "AuditLedger",
        back_populates="alert",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )

    __table_args__ = (
        Index("ix_alerts_camera_detected", "camera_id", "detected_at"),
        Index("ix_alerts_type_severity", "alert_type", "severity"),
        Index("ix_alerts_status_detected", "status", "detected_at"),
        Index("ix_alerts_track", "track_id"),
        UniqueConstraint("uuid", name="uq_alerts_uuid"),
    )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary with datetime serialization."""
        data = super().to_dict()
        for key, value in data.items():
            if isinstance(value, datetime):
                data[key] = value.isoformat()
            elif isinstance(value, enum.Enum):
                data[key] = value.value
        return data


class AuditLedger(Base):
    """
    Tamper-evident audit ledger using SHA-256 chaining.

    Each block contains a hash of the previous block, creating an immutable chain.
    """

    __tablename__ = "audit_ledger"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(
        PG_UUID(as_uuid=False),
        unique=True,
        nullable=False,
        index=True,
    )

    # Block chain
    block_index: Mapped[int] = mapped_column(Integer, nullable=False, unique=True, index=True)
    previous_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    current_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)

    # References
    camera_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("cameras.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    alert_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("alerts.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Event data
    event_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    event_category: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    event_data: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False)

    # Cryptographic
    hash_algorithm: Mapped[str] = mapped_column(String(20), default="SHA256", nullable=False)
    signature: Mapped[Optional[str]] = mapped_column(String(256), nullable=True)
    public_key_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Timestamp
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # Relationships
    camera: Mapped[Optional["Camera"]] = relationship("Camera", back_populates="audit_logs")
    alert: Mapped[Optional["Alert"]] = relationship("Alert", back_populates="audit_logs")

    __table_args__ = (
        Index("ix_audit_camera_time", "camera_id", "timestamp"),
        Index("ix_audit_alert_time", "alert_id", "timestamp"),
        Index("ix_audit_block_chain", "block_index", "previous_hash"),
        UniqueConstraint("uuid", name="uq_audit_uuid"),
        UniqueConstraint("current_hash", name="uq_audit_current_hash"),
    )

    @staticmethod
    def compute_hash(
        block_index: int,
        previous_hash: str,
        event_type: str,
        event_category: str,
        event_data: dict[str, Any],
        timestamp: datetime,
    ) -> str:
        """
        Compute SHA-256 hash for a ledger block.

        Args:
            block_index: Sequential block number.
            previous_hash: Hash of previous block.
            event_type: Type of event.
            event_category: Category of event.
            event_data: Event payload.
            timestamp: Block timestamp.

        Returns:
            Hex-encoded SHA-256 hash.
        """
        # Deterministic serialization
        data = {
            "index": block_index,
            "prev": previous_hash,
            "type": event_type,
            "category": event_category,
            "data": event_data,
            "ts": timestamp.isoformat() if isinstance(timestamp, datetime) else timestamp,
        }
        serialized = json.dumps(data, separators=(",", ":"), sort_keys=True).encode("utf-8")
        return hashlib.sha256(serialized).hexdigest()

    def verify_chain(self, previous_block: Optional["AuditLedger"] = None) -> bool:
        """
        Verify this block's hash and chain integrity.

        Args:
            previous_block: Previous block in chain (optional).

        Returns:
            True if valid.
        """
        # Verify current hash
        expected = self.compute_hash(
            self.block_index,
            self.previous_hash,
            self.event_type,
            self.event_category,
            self.event_data,
            self.timestamp,
        )
        if expected != self.current_hash:
            return False

        # Verify chain link
        if previous_block:
            if self.previous_hash != previous_block.current_hash:
                return False
            if self.block_index != previous_block.block_index + 1:
                return False

        return True

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary with datetime serialization."""
        data = super().to_dict()
        for key, value in data.items():
            if isinstance(value, datetime):
                data[key] = value.isoformat()
            elif isinstance(value, enum.Enum):
                data[key] = value.value
        return data


@dataclass(frozen=True, slots=True)
class LedgerBlock:
    """
    In-memory representation of a ledger block for building chain.

    Used by the ledger service before persisting.
    """

    block_index: int
    previous_hash: str
    event_type: str
    event_category: str
    event_data: dict[str, Any]
    timestamp: datetime
    camera_id: Optional[int] = None
    alert_id: Optional[int] = None
    hash_algorithm: str = "SHA256"
    signature: Optional[str] = None
    public_key_id: Optional[str] = None

    def compute_hash(self) -> str:
        """Compute block hash."""
        return AuditLedger.compute_hash(
            self.block_index,
            self.previous_hash,
            self.event_type,
            self.event_category,
            self.event_data,
            self.timestamp,
        )

    def to_orm(self) -> AuditLedger:
        """Convert to ORM model."""
        current_hash = self.compute_hash()
        return AuditLedger(
            uuid=f"{current_hash[:8]}-{int(time.time() * 1000)}",
            block_index=self.block_index,
            previous_hash=self.previous_hash,
            current_hash=current_hash,
            camera_id=self.camera_id,
            alert_id=self.alert_id,
            event_type=self.event_type,
            event_category=self.event_category,
            event_data=self.event_data,
            hash_algorithm=self.hash_algorithm,
            signature=self.signature,
            public_key_id=self.public_key_id,
            timestamp=self.timestamp,
        )


# Event categories for audit ledger
class AuditEventCategory(enum.Enum):
    """Categories of events logged to audit ledger."""

    SYSTEM = "system"
    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    DATA_ACCESS = "data_access"
    DATA_MODIFICATION = "data_modification"
    CONFIGURATION = "configuration"
    ALERT = "alert"
    CAMERA = "camera"
    GEOFENCE = "geofence"
    WATCHLIST = "watchlist"
    KEY_MANAGEMENT = "key_management"


class AuditEventType(enum.Enum):
    """Specific event types for audit logging."""

    # System
    SYSTEM_START = "system_start"
    SYSTEM_STOP = "system_stop"
    CONFIG_CHANGE = "config_change"

    # Authentication
    LOGIN_SUCCESS = "login_success"
    LOGIN_FAILED = "login_failed"
    TOKEN_REFRESH = "token_refresh"
    TOKEN_REVOKED = "token_revoked"

    # Authorization
    PERMISSION_GRANTED = "permission_granted"
    PERMISSION_DENIED = "permission_denied"
    ROLE_CHANGED = "role_changed"

    # Data
    ALERT_CREATED = "alert_created"
    ALERT_ACKNOWLEDGED = "alert_acknowledged"
    ALERT_RESOLVED = "alert_resolved"
    ALERT_ESCALATED = "alert_escalated"

    # Camera
    CAMERA_REGISTERED = "camera_registered"
    CAMERA_UPDATED = "camera_updated"
    CAMERA_DECOMMISSIONED = "camera_decommissioned"
    CAMERA_HEARTBEAT = "camera_heartbeat"
    CAMERA_STATUS_CHANGE = "camera_status_change"

    # Geofence
    GEOFENCE_CREATED = "geofence_created"
    GEOFENCE_UPDATED = "geofence_updated"
    GEOFENCE_DELETED = "geofence_deleted"
    GEOFENCE_INTRUSION_LOGGED = "geofence_intrusion_logged"

    # Watchlist
    WATCHLIST_ADDED = "watchlist_added"
    WATCHLIST_REMOVED = "watchlist_removed"
    WATCHLIST_MATCH = "watchlist_match"

    # Keys
    KEY_ROTATED = "key_rotated"
    KEY_REVOKED = "key_revoked"


# Export all
__all__ = [
    "Base",
    "Camera",
    "CameraStatus",
    "Alert",
    "AlertSeverity",
    "AlertType",
    "AlertStatus",
    "ConsensusStatus",
    "AuditLedger",
    "LedgerBlock",
    "AuditEventCategory",
    "AuditEventType",
]


if __name__ == "__main__":
    # Demo - show model structure
    print("=== Camera Model ===")
    for col in Camera.__table__.columns:
        print(f"  {col.name}: {col.type} {'PK' if col.primary_key else ''} {'FK' if col.foreign_keys else ''}")

    print("\n=== Alert Model ===")
    for col in Alert.__table__.columns:
        print(f"  {col.name}: {col.type} {'PK' if col.primary_key else ''} {'FK' if col.foreign_keys else ''}")

    print("\n=== AuditLedger Model ===")
    for col in AuditLedger.__table__.columns:
        print(f"  {col.name}: {col.type} {'PK' if col.primary_key else ''} {'FK' if col.foreign_keys else ''}")

    # Test hash computation
    block = LedgerBlock(
        block_index=1,
        previous_hash="0" * 64,
        event_type=AuditEventType.ALERT_CREATED.value,
        event_category=AuditEventCategory.ALERT.value,
        event_data={"alert_id": 123, "camera_id": 1},
        timestamp=datetime.utcnow(),
    )
    print(f"\nTest block hash: {block.compute_hash()}")